### ISSUE TITLE
Question about the usage of the renderer

### ISSUE THREAD

**Issue by rjoaopereira** [kyle-mccarthy/nest-next#47]
Hi @kyle-mccarthy! Thanks for sharing this module.

I have a use case where I don't want to descriminate the pages in the controller that uses the renderer. I want it to be a catch all.

At first sight, it seems as everything was ok, but then I noticed that the assets were not being served.

A little investigation led me to learn that next's render method is only suited for pages although it also serves assets if they are from `_next` or from `static` folder.

With the advent of the public folder this behaviour broke because the render method does not cater to it.

I am left with two solutions.

1. Enumerate all possible routes in the controller and let the filter catch the rest
2. Use the RenderService's `getRequestHandler` which is an all purpose method.

I'm going with the latter which brings me to the question. Why not use it always and avoid the filter?

**Comment by kyle-mccarthy** [comment]
Hey thanks for checking it out. I don't exactly have a solution for you but can give you some more info and potential problems you may encounter.

So how the package currently works is that nest is responsible for the http server and initially handles the incoming request and performs all the routing. If the request doesn't have a route then nest throws an `NotFoundException`. That is where the RenderFilter comes into play because next's internal urls like `/_next/*` or `/_static/*` don't have a matching route as far as nest is concerned but they do with next so the request is forwarded on to next. If the request doesn't match an internal next url then there is some processing done on the error to remove anything that can't be serialized and then calls next's error handler and then nest is done with that request. So some sort of filter is needed so next can get the requests for it's internal assets.

One possible solution I can think of is in the filter have it call next's request handler for any error that has a status of 404 or is an instance of `NotFoundException`. However, this will break any 404s that you intentionally throw. So if you have an api route like `/user/5` and there isn't a user with id 5 and want to throw a 404 via nest, it would still go onto be handled by next.

One other possibility wouldn't involve the nest-next package but could still work. Instead of having nest be responsible for the routing/initial entry point, you could reverse it have next handle it and then use [nest's standalone application](https://docs.nestjs.com/standalone-applications) to access nest's infrastructure. Then you could use next's [built in api routing](https://nextjs.org/docs/api-routes/introduction) and [the newly added getServerSideProps function](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) and get an instance of your nest app.

The second idea could be interesting since you wouldn't have to do a custom server, but you would lose out on things that best automatically handles for you, specifically as far as the routing goes.

**Comment by rjoaopereira** [comment]
Thank you for your explanation on the inner workings of the module.

As for the proposed solutions, I am actually keener on the first. My reasoning is that:
- I prefer nest on the front and next as a catchall
- the 404 handled by next makes sense to me even if an API route is called. My use case is not of a pure API server. I have an app which has an API for app consumption. The format of the 404 response is not relevant.

But the solution I currenlty have is, on a nest catch all controller to handle the response by relaying it to the the module's render service `getRequestHandler`.
This covers all my needs as the catch all is added as the last route. As such, all routes I need to declare are fully functional, all else is handled by next.

I actually think that you could have this as a rule for all response handling in the module and remove `app.render` as it is too specific for pages. the `requestHandler` handles all cases. 
This would remove the need for the filter. Users of the module would not need to use the `render` method of the response and just return the result of the handler. It deviates from nest's structure of MVC but still adheres to the concept.

In any case, it is just a use case and the solution works for me. Maybe it would work for others.

Thanks for the awesome work!
