### ISSUE TITLE
How to exclude routes from this module

### ISSUE THREAD

**Issue by Israel001** [kyle-mccarthy/nest-next#64]
I am trying to block this module from handling some specific routes. Please how can I achieve that.

**Comment by kyle-mccarthy** [comment]
Hey this functionality is currently exposed on the 'next` branch, you can see my comment [here](https://github.com/kyle-mccarthy/nest-next/issues/38#issuecomment-647867509) for more info.

I am planning on mastering this, but am waiting on community feedback to make sure it didn't introduce any unforeseen problems.

**Comment by Israel001** [comment]
Hi, 

I think you misunderstood my question. I am not trying to make this module forward my routes automatically to Next.

I am trying to skip the whole Next middleware altogether. I have a route that is supposed to be handled by another package, but Next keeps interrupting and returning ```404 not found``` instead.

**Comment by kyle-mccarthy** [comment]
How do you have the other package working with nest?

**Comment by Israel001** [comment]
I am using the traditional ```use``` method. Something like this:
```
app.use('/monitor', packageConfig);
```

**Comment by kyle-mccarthy** [comment]
Are you using fastify or express? And does your middleware work without nest-next?

**Comment by Israel001** [comment]
I am using express. And yes, my middleware works without ```nest-next```

**Comment by kyle-mccarthy** [comment]
Can you show me how your middleware works? The render filter ignores the request [if the headers have already been sent](https://github.com/kyle-mccarthy/nest-next/blob/2bf771e3d68aa37f51fe0ed81fbc6c52c92ea199/lib/render.filter.ts#L71). So that makes me think that it isn't sending a response.

Additionally, I would be curious to see if adding a custom error handler intercepted the error.

If you provide a minimal reproducible example in a repository I can try to help figure out what the problem is.

**Comment by Israel001** [comment]
Okay, here is a repository: https://github.com/Israel001/nest-issue 

If you try to access ```/monitor``` it says ```404 not found``` but if you uncomment the render module, it works.

**Comment by kyle-mccarthy** [comment]
@Israel001 okay so I figured out the problem, [the bull-arena package tries to use the hbs templating engine](https://github.com/bee-queue/arena/blob/6fc5860f55c54e0dfb3fcab58de2b3fc9556c26e/src/server/app.js#L30) provided by express; however, nest-next overrides that to allow rendering to be done by nextjs. 

By overriding the `render` method on the response, it allows for this package (nest-next) to easily expose next as the renderer through nest's Render decorator as well through `res.render` function, [see the docs about rendering](https://github.com/kyle-mccarthy/nest-next#rendering-pages).

I think there are two options in this scenario:

1. It may be possible for nest-next to expose a config option to not override the express response render function, but IIRC that would mean you would have to use the `@Render` decorator. 
2. I could probably also allow for you to specify an alternative name for next's render method on the response. I.e you would specify a name like `renderSSR` and then call `res.renderSSR` instead of `res.render`.

Let me know if either of those sound good or if you have any alternative suggestions.

**Comment by Israel001** [comment]
Oh, I see. I can't imagine how any of these options will be applied to fix the issue from usage perspective lol.

Anyway, I've found another package that doesn't try to use hbs templating engine, and it's working fine now.
