### ISSUE TITLE
RenderService.setErrorHandler not working

### ISSUE THREAD

**Issue by DiFuks** [kyle-mccarthy/nest-next#65]
I need custom nest error handling for logging and custom response. The documentation has a section on this: https://github.com/kyle-mccarthy/nest-next#handling-errors

_I am going to use your library on a very large production project. So I really need help. If you point out what the problem is, I could help you solve it. And further help the development of your project_

Example of my code:

```ts
// main.ts
async (): Promise<void> => {
  const app = await NestFactory.create(AppModule);

  const renderService = app.get(RenderService);

  renderService.setErrorHandler((err, req, res) => {
    console.log(err);

    res.send({
      error: 'Test',
    });
  });

  await app.listen(3000);
})();
```

```tsx
export const About: FC = () => {
  throw new Error('Test error');

  return (
    <div>Sample feature</div>
  );
};
```

In dev mode, as a response, I get the default error page, but the callback is executed:
![image](https://user-images.githubusercontent.com/12777199/98967639-c12a8280-251d-11eb-80f0-fc3b7caa88c0.png)

But the following errors get to the console:
![image](https://user-images.githubusercontent.com/12777199/98968389-aefd1400-251e-11eb-89cf-b4f1bd9095f2.png)

In the browser:
![image](https://user-images.githubusercontent.com/12777199/98968445-bde3c680-251e-11eb-9ac9-da1de4ff9e97.png)

In prod mode, no callback is executed at all. The browser displays a standard error page.

-------

I also want to add that when using the global error handler, page rendering stops working. As I understand it, your library uses its own global error handler. I managed to solve this problem in this way:

```ts
// main.ts
(async (): Promise<void> => {
  const app = await NestFactory.create(AppModule);

  const errorFilter = app.select(ErrorFilterModule).get(ErrorFilter);

  const renderFilter = app.get(RenderFilter);

  errorFilter.setRenderFilter(renderFilter);

  app.useGlobalFilters(errorFilter);

  await app.listen(3000);
})();
```

```ts
export class ErrorFilter implements ExceptionFilter {
  private renderFilter: RenderFilter;

  public constructor(
    // ...
  ) {}

  public setRenderFilter(renderFilter: RenderFilter): void {
    this.renderFilter = renderFilter;
  }

  public async catch(error: Error, host: ArgumentsHost): Promise<void> {
    // ...

    if (req.path.includes('_next')) {
      await this.renderFilter.catch(error, host);

      return;
    }

    // ...
  }
}
```

------

An example of my code where the problem is reproduced: https://github.com/DiFuks/react-next-nest-boilerplate

To run a project:

1. cp .env.dist .env
2. npm run dev
3. Open 127.0.0.1:3000/sample

For production build:

1. Change the value of the NODE_ENV parameter in the .env file to "production"
2. npm run prod

The file in which the error is thrown: 
https://github.com/DiFuks/react-next-nest-boilerplate/blob/master/src/features/About/About.tsx

main.ts file:
https://github.com/DiFuks/react-next-nest-boilerplate/blob/master/src/server/main.ts

**Comment by kyle-mccarthy** [comment]
Hey I wanted to let you know that I looked into this, it's a good question and I hand't actually had this come up before. The tl;dr is that since you're throwing the error in the actual NextPage so next's renderer is handling the error and not throwing it back out to nest/nest-next. 

This package exposes next's render on the response by overriding the default server's render function, this is done in the [RenderService](https://github.com/kyle-mccarthy/nest-next/blob/2bf771e3d68aa37f51fe0ed81fbc6c52c92ea199/lib/render.service.ts#L228). This is then exposed via the Render decorator as well as on a property on the response (`res.render`). Once this is called, next then takes over the responsibility of rendering the page and sending the response. 

Since next takes over the request, without really any idea of what we've done, it also takes responsibility of handling any exceptions that are thrown from that point on. Without handling the exceptions, any error thrown during its rendering process would result in an unhandled exception. If an error is thrown during this phase, next will set the response code and everything and then uses its Error page. I'm not sure if this will help do what you're wanting, but you do have the option of overriding the default error page though and using your own, [here are the docs for that](https://nextjs.org/docs/advanced-features/custom-error-page).

Out of curiosity, what is the purpose of [GetPageWithApi](https://github.com/DiFuks/react-next-nest-boilerplate/blob/b457c84970e756a3c53dd2bd96dd99e83427fbdf/src/server/Page/decorators/GetPageWithApi.ts)? Are you trying to use Next's API routes?

**Comment by DiFuks** [comment]
@kyle-mccarthy Thanks for the answer! Unfortunately, overriding the page error is not enough functionality for me. At least, due to the fact that it does not work in dev mode. And it doesn't provide enough flexibility. But I will try to solve this problem somehow.
[GetPageWithApi](https://github.com/DiFuks/react-next-nest-boilerplate/blob/master/src/server/Page/decorators/GetPageWithApi.ts) is used in conjunction with [FormatResponse](https://github.com/DiFuks/react-next-nest-boilerplate/blob/master/src/server/Page/interceptors/FormatResponse.ts) interceptor. When the user opens the page, all the data goes into the "query" parameter. But when switching between pages, you need to request the same data, but from the frontend. Therefore, if the page was opened at /sample, then the data for its rendering will be requested at /api/page/sample. This ensures data consistency for page initialization - https://github.com/DiFuks/react-next-nest-boilerplate/blob/master/src/pages/views/Sample/Index.tsx#L20

**Comment by kyle-mccarthy** [comment]
Okay that makes sense to me, this would be a good use case for next's [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering). Unfortunately, when I created nest-next it was before that was added so it doesn't really take that or the API routes into account. I do have a pretty good idea of how I could implement this package to be aware of the new next features, but it would fundamentally change how it works.
