### ISSUE TITLE
Flash of Unstyled Content while using customized _document

### ISSUE THREAD

**Issue by ithinco** [kyle-mccarthy/nest-next#8]
It seems that the customized _document hasn't been attached to the renderOpts in renderToHTML function  of next-server.

```
func renderToHTML(req, res, pathname, query, renderOpts) {}
```

I'm using "next": "8"

**Comment by kyle-mccarthy** [comment]
Hi can you provide a little more information about how you are handling your styles? I use emotion 10 and haven't encountered this issue. I also don't directly call the renderToHTML method, I call render.

**Comment by ithinco** [comment]
Hi, @kyle-mccarthy I'm using material-ui and this _document.tsx setting. https://github.com/mui-org/material-ui/blob/next/examples/nextjs-next-with-typescript/pages/_document.tsx 

BTW, Thanks for your work.

**Comment by kyle-mccarthy** [comment]
Thanks for sending that over. Unfortunately it looks like the example they provided is wrong. The call renderPage directly from the context, rather than using the enhancer which can cause the flash reported in [this issue](https://github.com/zeit/next.js/issues/5629) on the nextjs repo.

I messed around with their material-next example a little bit and was able to get it working with the enhanceApp, [here is the gist](https://gist.github.com/kyle-mccarthy/3169001e052a8fa0da455d4f9ed1a6ed). However, it looks like V4 uses a new SSR API, so this will likely not work when they release the new version in a couple of days.

Since this isn't really related to this repo, and is more of a question about using material-ui with next I am going to close this issue. I encourage you to ask the material-ui devs about an alternative to calling renderPage directly, since other people probably are having the same issue. You may want to attach the nextjs issue ([#5629](https://github.com/zeit/next.js/issues/5629)) I referenced above.
